
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: docker images -a
      - run: docker-compose --verbose run ruby_script
      - run: docker images -a
      - run: docker-compose --verbose run --build ruby_script
      - run: docker images -a
